### ISSUE TITLE
Issue with getid3

### ISSUE THREAD

**Issue by StoryHack** [lrkrol/Noctifer-Music#1]
If you install this onto a server that is running php 7.4 or 8.0, the getid3 code throws several errors when you try to play a file. 

I swapped in the newest version of getid3 (1.9.20) from http://getid3.sourceforge.net/ and everything started working. So the copy of getid3 here in the repo should probably be updated.

Thanks for releasing this!

**Comment by lrkrol** [comment]
Thanks @StoryHack for pointing this out -- indeed getid3 was out of date. I have uploaded 1.9.20 to the current branch.
