### ISSUE TITLE
White screen/no code after incorrect password

### ISSUE THREAD

**Issue by MassInsanity** [lrkrol/Noctifer-Music#10]
I'm having an issue with this code - when a user enters in a "wrong" password... it reloads the page to a blank white screen.

**Comment by MassInsanity** [comment]
Your demo does the same thing.

**Comment by lrkrol** [comment]
Thanks for pointing this out! It has been fixed in the recent release, [v0.7.3](https://github.com/lrkrol/Noctifer-Music/releases/tag/v0.7.3).
