### ISSUE TITLE
#9 Dream Errors Out

### ISSUE THREAD

**Issue by TheBlode** [lrkrol/Noctifer-Music#11]
Good afternoon!

I really love your creation here and I'm enjoying it. I've forked it for myself and I plan on customizing it to suit my own tastes and add logging of plays too something which I personally love see.

I can see that the program simply doesn't play John Lennon's classic song "#9 Dream". I suspect it's because of the hash symbol so maybe sanitizing that character would fix the problem. I thought I'd share with you. I'm happy to provide a patch if you'd like. Just let me know.

![image](https://user-images.githubusercontent.com/59338703/221425154-a1fc911c-0b3f-4127-8840-ccb9a8668119.png)

And thanks again for this wonderful creation.

All the best,
Blode.

**Comment by lrkrol** [comment]
Thanks, Blode, for your kind words and your report of this issue. The # is apparently one of those characters HTML is not very happy with. I believe I have fixed it now with the recent [release v0.7.3](https://github.com/lrkrol/Noctifer-Music/releases/tag/v0.7.3) by encoding the file name when loading it. Let me know if that works for you, too!
