### ISSUE TITLE
play stop

### ISSUE THREAD

**Issue by Rus2011** [lrkrol/Noctifer-Music#16]
medialink.mytestdomain.pro
for tested hosting

At first it worked, now it stops after each song - you need to start it again yourself.

**Comment by Rus2011** [comment]
Is it possible to create a playlist link for AIMP?

**Comment by Rus2011** [comment]
https://mediateka.link/
disable cash nginx

the best WORK

**Comment by lrkrol** [comment]
I cannot verify anything since the links are unfortunately down, but I suspect the first issue is due to #4. I'll close this; you're invited to re-open a new issue if you run into something again.
